## 'makeCacheMatrix' and 'cacheSolve' work together to calculate the
## inverse matrix of a matrix input and store the solution in R cache
## for quick retrieval across all environments in an R session.

## 'makeCacheMatrix' is a function that takes a matrix 'x' as input
## and stores a list of functions in R cache to be accessible across
## different R environments.  The functions stored are:
## 
## 1. set the value of the matrix
## 2. get the value of the matrix
## 3. set the value of the matrix inverse (using the solve function)
## 4. get the value of the matrix inverse

makeCacheMatrix <- function(x = matrix()) {
     m <- NULL
     set <- function(y) {
          x <<- y
          m <<- NULL
     }
     get <- function() x
     setinv <- function(solve) m <<- solve
     getinv <- function() m
     list(set = set, get = get,
          setinv = setinv,
          getinv = getinv)
}


## 'cacheSolve' takes a list of functions generated by 'makeCacheMatrix'
## as an input, then checks R cache to see if the solution (the inverse matrix)
## has already been calculated and stored.  If the solution has been stored,
## then it is retrieved.  Otherwise, 'cacheSolve' calls 'makeCacheMatrix' and
## stores the solution in R cache for quicker retrieval later in your existing
## session.  Finally, the solution is returned to the console in the current
## environment.

cacheSolve <- function(x, ...) {
     m <- x$getinv()
     if(!is.null(m)) {
          message("getting cached data")
          return(m)
     }
     data <- x$get()
     m <- solve(data, ...)
     x$setinv(m)
     m
}
